-- Initial SafeHub client table. Apply this migration before using /api/v1/clientes.
create table if not exists public.clientes (
  id integer generated by default as identity primary key,
  nome text not null,
  setor text,
  status_pipeline text not null default 'novo',
  responsavel_id integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  constraint clientes_nome_not_blank check (length(trim(nome)) > 0),
  constraint clientes_status_not_blank check (length(trim(status_pipeline)) > 0)
);

create index if not exists clientes_active_order_idx
  on public.clientes (id desc)
  where archived_at is null;

create index if not exists clientes_active_responsavel_idx
  on public.clientes (responsavel_id)
  where archived_at is null;
